### ISSUE TITLE
create_video_sample issue

### ISSUE THREAD

**Issue by lele2386** [AlanNaoto/carla-dataset-runner#4]
first thanks AlanNaoto for this great work 
i use your code to collect data from carla 0.9.6 and it work with me but when i want to record a video from caral there is an error and i tried to fix it but still it is not work so if you know where is the problem please tell me 
Thanks in advance
File "main.py", line 92, in <module>
    create_video_sample(os.path.join('data', args.hdf5_file + ".hdf5"), show_depth=args.depth)
File "/home/lele/Desktop/carla-dataset-runner-master/create_content_on_hdf5.py", line 70, in create_video_sample
    rgb_data = np.array(file['rgb'][str(time)])
KeyError: "Unable to open object (object '1581078279422.0' doesn't exist)"

**Comment by AlanNaoto** [comment]
Could you share the commands you issued to run the program?

**Comment by lele2386** [comment]
$ python main.py hdf5_file -ve 100 -wa 110 -v

**Comment by AlanNaoto** [comment]
I think there might be an issue with the timestamps in the created HDF5 file. In the context of this snippet of code on create_content_on_hdf5.py:
`rgb_data = np.array(file['rgb'][str(time)])`
what I am doing is cycling through the timestamps in the HDF5 file and getting the RGB data according to each timestamp. 

Woud you mind either sharing with me the created HDF5 file in the 'data' dir or showing pictures of the contents of the 'timestamps' and 'rgb' dataset? (like this:)

![Screenshot from 2020-02-07 14-31-43](https://user-images.githubusercontent.com/33168106/74033686-fe724a80-49b6-11ea-8421-a9973070c515.png)

![Screenshot from 2020-02-07 14-33-59](https://user-images.githubusercontent.com/33168106/74033697-03cf9500-49b7-11ea-81a5-ff0f08b2b3b5.png)

**Comment by lele2386** [comment]
![Screenshot from 2020-02-07 15-43-18](https://user-images.githubusercontent.com/60781620/74034267-9d4f7480-49c0-11ea-9cd0-3c89a3b57e0a.png)
![Screenshot from 2020-02-07 15-44-03](https://user-images.githubusercontent.com/60781620/74034304-afc9ae00-49c0-11ea-8c99-c9c2a0e99a1b.png)

**Comment by AlanNaoto** [comment]
Okay. Try changing this line of code here:
https://github.com/AlanNaoto/carla-dataset-runner/blob/3477d6b1660219e606f6376c302618d0e1706537/CarlaWorld.py#L159 for
`timestamp = int(round(time.time() * 1000.0))`
And then rerun the simulator and data collection script. Please let me know if it worked. :confused:

**Comment by lele2386** [comment]
thanks alan for your help it worked finally

**Comment by AlanNaoto** [comment]
Nice! I'm closing this issue then.
